name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Package
        run: |
          ls -la
          chmod +x .github/workflows/scripts/build_pkg.sh
          bash .github/workflows/scripts/build_pkg.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        files: |
          ./dist/*.zip
        draft: false
        prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
